name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-python-conda:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: dronerl-env-v3
        environment-file: environment.yml
        auto-activate-base: false

    - name: Run Tests
      shell: bash -l {0}
      env:
        ARTIFACTS_DIR: ${{ github.workspace }}/artifacts
      run: |
        conda activate dronerl-env-v3
        mkdir -p $ARTIFACTS_DIR
        pytest tests/torch_tests

    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test-videos-conda
        path: ${{ github.workspace }}/artifacts/*.mp4

  test-python-pip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r torch_impl/requirements.txt

    - name: Run Tests
      env:
        ARTIFACTS_DIR: ${{ github.workspace }}/artifacts
      run: |
        mkdir -p $ARTIFACTS_DIR
        pytest tests/torch_tests

    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test-videos-pip
        path: ${{ github.workspace }}/artifacts/*.mp4

  test-jax-pip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r jax_impl/requirements.cpu.txt

    - name: Run Tests
      run: pytest tests/jax_tests

  test-common-pip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r torch_impl/requirements.txt
        pip install -r jax_impl/requirements.cpu.txt

    - name: Run Tests
      run: pytest tests/test_*.py
